In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

In [5]:
#Load the dataset
data=pd.read_csv("customer.csv")
data.head()

Customer ID             Name  Age  Income  Purchase History
0            1         John Doe   30   50000                 5
1            2       Jane Smith   25   60000                 3
2            3  Michael Johnson   40   75000                 8
3            4      Susan Brown   35   55000                 4
4            5        David Lee   28   60000                 6

In [6]:
data.shape

(100, 5)

In [7]:
data.describe()

Customer ID         Age        Income  Purchase History
count   100.000000  100.000000    100.000000         100.00000
mean     50.500000   33.350000  66610.000000           5.97000
std      29.011492    6.074246  11639.270865           2.21772
min       1.000000   22.000000  48000.000000           2.00000
25%      25.750000   28.750000  55750.000000           4.00000
50%      50.500000   32.000000  65500.000000           6.00000
75%      75.250000   38.000000  76000.000000           8.00000
max     100.000000   49.000000  90000.000000          10.00000

In [8]:
data.isna().sum()

Customer ID         0
Name                0
Age                 0
Income              0
Purchase History    0
dtype: int64

In [11]:
x=data.iloc[:,2:4]
x.head()

Age  Income
0   30   50000
1   25   60000
2   40   75000
3   35   55000
4   28   60000

In [15]:
y=data.iloc[:,-1:]
y.head()

Purchase History
0                 5
1                 3
2                 8
3                 4
4                 6

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=2)
print("********Training Data Shape**********")
print('Training data-x-Shape:',xtrain.shape)
print('Training data-y-Shape:',ytrain.shape)
print("********Testing Data Shape**********")
print('Testing data(X-Input) Shape:',xtest.shape)
print('Testing data(y-Outcome) Shape:',ytest.shape)

********Training Data Shape**********
Training data-x-Shape: (80, 2)
Training data-y-Shape: (80, 1)
********Testing Data Shape**********
Testing data(X-Input) Shape: (20, 2)
Testing data(y-Outcome) Shape: (20, 1)


In [17]:
knn_model=KNeighborsClassifier(n_neighbors=3)
print('**********KNN Classifier Model**********')
print("Training Phase\n")
knn_model.fit(xtrain,ytrain)
print("Training is completed")
print("="*100)
print("Testing Phase\n")
ypred=knn_model.predict(xtest)
print("Predicted Class Label are:",ypred)
print('Test is also done')
print("="*100)

**********KNN Classifier Model**********
Training Phase

Training is completed
Testing Phase

Predicted Class Label are: [ 3  2  4  7  5  9  6  4  6 10  5  6  9  6  2  3  3  7  8  8]
Test is also done


C:\Users\SIRISHA\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [24]:
#feature scaling
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.fit_transform(xtest)
#print(xtrain)
#print(xtest)

In [28]:
xtrain.shape

(80, 2)

In [29]:
xtrain[0]

array([-1.18791908, -0.68638518])

In [30]:
#subtract 1 from the rootvalue to get odd number to perform better
import math
math.sqrt(len(ytest))

4.47213595499958

In [32]:
classifier=KNeighborsClassifier(n_neighbors=3,p=2,metric='euclidean')
classifier.fit(xtrain,ytrain)

C:\Users\SIRISHA\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [33]:
ypred=classifier.predict(xtest)
ypred

array([ 3,  2,  3,  7,  5,  9,  5,  3,  6, 10,  5,  6,  9,  8,  3,  3,  4,
        7,  7,  8], dtype=int64)

In [34]:
#Evaluate model
cm=confusion_matrix(ytest,ypred)
cm

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2, 2, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix
accuracy = accuracy_score(ytest,ypred)

# Calculate precision for each class and get the average
precision = precision_score(ytest,ypred,average='macro')

# Calculate recall for each class and get the average
recall = recall_score(ytest,ypred, average='macro')

# Calculate F1-Score for each class and get the average
f1 = f1_score(ytest,ypred,average='macro')



# Print the metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.35
Precision: 0.4296296296296296
Recall: 0.25
F1 Score: 0.27989417989417986


C:\Users\SIRISHA\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
