# 1. Create a 3 x 3 x 3 array with random values

In [12]:
import numpy as np
array=np.random.random((3,3,3))
print(array)
np.ndim(array)

[[[0.85887746 0.97229672 0.00343349]
  [0.88710438 0.29366692 0.61562693]
  [0.2032968  0.03254088 0.76660874]]

 [[0.79900224 0.13714697 0.87069256]
  [0.74503111 0.23435305 0.99237637]
  [0.99324978 0.03179033 0.67583545]]

 [[0.94230067 0.31431567 0.55355076]
  [0.15695701 0.42913222 0.69605722]
  [0.72507255 0.41780905 0.66242187]]]


3

# 2.Create a 5 x 5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
array=np.zeros((5,5))
for i in range(1,5):
    array[i,i-1]=i
print(array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8 x 8 matrix and fill it with a checkerboard pattern

In [54]:
array=np.zeros((8,8),dtype=int)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5 x 5 random matrix

In [57]:
import numpy as np

# Create a 5x5 random matrix with values between 0 and 1
random_matrix = np.random.random((5, 5))

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix to have mean 0 and standard deviation 1
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.89352467 0.74559987 0.64423944 0.45500181 0.81376224]
 [0.78727602 0.48401484 0.36898506 0.87833334 0.63475617]
 [0.00193071 0.68262574 0.81905205 0.3964481  0.87719788]
 [0.79423222 0.06343745 0.4965055  0.50584715 0.63099634]
 [0.36414175 0.86859576 0.78782043 0.09057878 0.11031614]]

Normalized Matrix:
[[ 1.19094265  0.65007263  0.27945991 -0.41246568  0.89930052]
 [ 0.80245671 -0.30638288 -0.72697602  1.13539729  0.24478541]
 [-2.06906801  0.41981501  0.9186421  -0.62656059  1.13124562]
 [ 0.82789122 -1.84417566 -0.26071223 -0.22655558  0.23103804]
 [-0.74468503  1.09979296  0.80444728 -1.74493652 -1.67276916]]


# 5. How to find common values between two arrays?

In [69]:
array1 = np.array([1, 7, 3, 9, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)
print(common_values)


[3 5 7]


# 6. How to get the dates of yesterday, today and tomorrow?

In [71]:
import datetime

# Get the current date
today = datetime.date.today()

# Calculate the dates for yesterday and tomorrow
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [79]:
# Create two random arrays A and B 
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

# Check if A and B are equal
equal = np.array_equal(A, B)
if equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [82]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with the Maximum Value Replaced:")
print(random_vector)


Random Vector with the Maximum Value Replaced:
[0.15716709 0.52669615 0.8835886  0.16415051 0.5236441  0.23037497
 0.40190082 0.3366641  0.03585011 0.        ]


# 9. How to print all the values of an array?

In [98]:
# Create a NumPy array
array = np.array([1, 2, 3, 4])
for i in array:
    print(i)


1
2
3
4


# 10.Subtract the mean of each row of a matrix

In [99]:
import numpy as np

# Create a sample matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row (axis=1) and reshape it to a column vector
row_means = matrix.mean(axis=1, keepdims=True)

# Subtract the row means from the original matrix
matrix_centered = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(matrix_centered)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [104]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5, 6])

# Second vector containing indices (be careful with repeated indices)
indices = np.array([2, 4, 5])

# Add 1 to the elements at the specified indices
given_vector[indices] += 1

print("Updated Vector:")
print(given_vector)


Updated Vector:
[1 2 4 4 6 7]


# 12.How to get the diagonal of a dot product?

In [105]:
import numpy as np

# Create two example matrices A and B (replace these with your matrices)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of matrices A and B
dot_product = np.dot(A, B)

# Extract the diagonal elements of the dot product matrix
diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [124]:
import numpy as np
array = np.random.randint(0,10,50)
print( array)
most_frequent = np.argmax(np.bincount(array))
print('Most frequent value is:', most_frequent)

[4 3 1 4 2 8 8 5 9 7 0 2 3 8 7 7 0 3 1 6 8 1 7 9 4 6 5 5 9 8 1 7 5 5 5 6 2
 7 8 5 6 2 2 7 5 6 0 3 6 4]
Most frequent value is: 5


# 14.How to get the n largest values of an array

In [117]:
import numpy as np

# Create a NumPy array (replace with your own array)
my_array = np.array([4, 2, 7, 1, 9, 3, 6])

# Get the n largest values (e.g., n=3)
n_largest_values = np.partition(my_array, -3)[-3:]

print("N Largest Values:", n_largest_values)

N Largest Values: [6 7 9]


# 15.How to create a record array from a regular array?

In [123]:
import numpy as np

# Create a regular array
regular_array = [(1, "siri", 23),
                 (2, "anu", 30),
                 (3, "sita", 35)]

# Define the dtype and field names
dtype = [('id', int), ('name', 'U10'), ('age', int)]

# Create a record array
record_array = np.rec.array(regular_array, dtype=dtype)

# Access elements by field names
print("ID:", record_array.id)
print("Name:", record_array.name)
print("Age:", record_array.age)

ID: [1 2 3]
Name: ['siri' 'anu' 'sita']
Age: [23 30 35]


# 16. How to swap two rows of an array?

In [114]:
import numpy as np

# Create a sample 2D array (replace this with your own array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 1 and 2 (0-based indexing)
array[1], array[2] = array[2].copy(), array[1].copy()

# Print the array after swapping
print("Array After Swapping Rows 1 and 2:")
print(array)


Array After Swapping Rows 1 and 2:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [131]:
import numpy as np

# Create the original 2D array
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])
# Reshape the array to the next dimension (3D)
reshaped_array = x.reshape((x.shape[0], x.shape[1], 1))

print("Original 2D Array:")
print(x)

print("\nReshaped 3D Array:")
print(reshaped_array)

Original 2D Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped 3D Array:
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
